# -*- coding: utf-8 -*-
"""jifunzeConverter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDpfUq24XIlCT4GRMdR_xWTqvQ9LE7rc
"""

!pip install docxtpl
!pip install pdfminer.six

import os
from google.colab import files

# Import the required libraries
from docxtpl import DocxTemplate
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from io import StringIO

# Function to convert .doc file to .txt file
def convert_doc_to_txt(input_file, output_file):
  docx = DocxTemplate(input_file)
  docx.save(output_file)

# Function to convert .pdf file to .txt file
def convert_pdf_to_txt(input_file, output_file):
  with open(output_file, 'w') as output:
    manager = PDFResourceManager()
    converter = TextConverter(manager, output, laparams=LAParams())
    page_interpreter = PDFPageInterpreter(manager, converter)

    with open(input_file, 'rb') as input_file:
      for page in PDFPage.get_pages(input_file):
        page_interpreter.process_page(page)

# Get the list of files from the user
files = files.upload()

# Convert each file to .txt file
for filename, file_data in files.items():
  if filename.endswith('.docx'):
    output_filename = os.path.splitext(filename)[0] + '.txt'
    with open(output_filename, 'wb') as output_file:
      output_file.write(file_data)
      convert_doc_to_txt(output_filename, output_filename)
  elif filename.endswith('.pdf'):
    output_filename = os.path.splitext(filename)[0] + '.txt'
    with open(output_filename, 'w') as output_file:
      convert_pdf_to_txt(filename, output_filename)

# Download the converted files